### ISSUE TITLE
Vaulting over windows/barbless cades lets you go over barbed cades

### ISSUE THREAD

**Issue by Varen** [RMC-14/RMC-14#3369] opened 2024-07-28 12:54 UTC
## Description
The vaulting state ignores barbed wire.

**Reproduction**
Place barbed cade against vaultable window or next to another cade that has no barbs. Vault on it. Go over barbed cade. Magic!

**Additional context**
It make comtech sad.

**Comment by Vermidia** [comment] 2024-07-28 21:27
Dupe of #3031 I think

**Closed by Vermidia** 2024-07-28 21:27 UTC
Labels: Status: Untriaged
