### ISSUE TITLE
Dead Xenos Block Bullets

### ISSUE THREAD

**Issue by Kezu02** [RMC-14/RMC-14#3826] opened 2024-08-25 04:58 UTC
## Description

A spitter and drone body somehow turned into improvised walls for xenos to escape.

**Comment by Dutch-VanDerLinde** [comment] 2024-08-25 23:57
this is fixed latest update, can't reproduce

**Comment by Dutch-VanDerLinde** [comment] 2024-08-26 18:48
this happens randomly, sometimes xeno corpses block bullets, sometimes they dont, no idea why it happens

**Comment by Dutch-VanDerLinde** [comment] 2024-08-26 18:48
on a live game

**Comment by Dutch-VanDerLinde** [comment] 2024-08-26 18:49
was kinda like the weird parasite bug #3462

**Comment by DrSmugleaf** [comment] 2024-09-06 09:28
Fixed in https://github.com/RMC-14/RMC-14/commit/ed0f4a9959343ca981985563265e1500fee5db59

**Closed by DrSmugleaf** 2024-09-06 09:28 UTC
Labels: Issue: Bug
