### ISSUE TITLE
MP double doors are all access. 

### ISSUE THREAD

**Issue by troytroy400** [RMC-14/RMC-14#3974] opened 2024-09-09 21:26 UTC
## Description
Every double door in the brig and MP areas are all access while all the single doors are not. 

**Reproduction**
Attempt to open any brig/MP double door without an ID. 

**Screenshots**
![image](https://github.com/user-attachments/assets/3f54ee96-0530-459f-b408-e603f4e9314c)
![image](https://github.com/user-attachments/assets/2232d77a-0fd9-4b34-a8c2-efd05d68231b)

**Additional context**
N/A

- #2393

**Comment by Vermidia** [comment] 2024-10-07 20:24
Dupe of #3737 (all doors are effected)

**Closed by Vermidia** 2024-10-07 20:24 UTC
Labels: Status: Untriaged
