### ISSUE TITLE
Xenos can attack / build / do actions while resting

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#2744] opened 2024-07-02 06:20 UTC

**Comment by snebl** [comment] 2024-07-02 08:03
Duplicate of [#2382](https://github.com/RMC-14/RMC-14/issues/2382)

**Comment by ARMOKS** [comment] 2024-07-02 08:07
This one has a few more details, you can do all actions

**Closed** 2024-07-04 11:08 UTC
Labels: Status: Untriaged
