### ISSUE TITLE
trijent generator area doors are always powered

### ISSUE THREAD

**Issue by TheDoctor1977** [RMC-14/RMC-14#4467] opened 2024-10-14 06:11 UTC
cutting every wire does not depower it, rendering them impossible to deconstruct
i have not yet tested this on other doors, only the black ones located in the generator area (with the water and the repairable generators, same as the generators on the ship)
![rmcbug](https://github.com/user-attachments/assets/39c4c8a0-8a15-4ef7-8dd4-0520c4b961ea)

**Comment by TheDoctor1977** [comment] 2024-10-14 06:12
this may actually not have been trijent, i say that based solely off the fact there was a lot of water surrounding the generators (it was like midnight and i passed out in bed almost immediately after)

**Comment by Vermidia** [comment] 2024-10-18 01:54
Dupe of #4446

**Closed by Vermidia** 2024-10-18 01:54 UTC
Labels: Status: Untriaged
