### ISSUE TITLE
CIC double doors are all access. 

### ISSUE THREAD

**Issue by troytroy400** [RMC-14/RMC-14#4311] opened 2024-10-06 22:26 UTC
## Description
All the CIC double doors are all access instead of command locked.

**Reproduction**
Attempt to open any CIC double door without an ID.

**Screenshots**
N/A

**Additional context**
Relevant to - #2393

**Comment by Vermidia** [comment] 2024-10-07 20:23
Dupe of #3737 (all doors are effected)

**Closed by Vermidia** 2024-10-07 20:23 UTC
Labels: Status: Untriaged
