### ISSUE TITLE
adding a stock to a gun makes it a 2x2

### ISSUE THREAD

**Issue by deltanedas** [RMC-14/RMC-14#3233] opened 2024-07-23 16:58 UTC
## Description
you can put it in your bag armour or even helmet 
shotguns become 2x2 but client predicts it as 2x3 so its super cursed
![05:57:18](https://github.com/user-attachments/assets/d6f3f718-741c-4f95-960e-e293b45f2d54)

**Comment by Vermidia** [comment] 2024-07-23 18:36
dupe of #3150

**Closed by Vermidia** 2024-07-23 18:36 UTC
Labels: Status: Untriaged
