### ISSUE TITLE
Dead infested larva able to burst

### ISSUE THREAD

**Issue by KittenColony** [RMC-14/RMC-14#3869] opened 2024-08-29 06:07 UTC
## Description
Larvae killed via grenades next to their host are still able to develop, and are able to burst out, but are considered DEAD, resulting in a net loss of 1 for both sides

**Reproduction**
grenade an infested corpse

**Additional context**
Witnessed a squad leader's corpse be recovered via grenading the body out of the nest, the larva developed, I was able to take control and burst despite being dead inside the host

**Comment by Vermidia** [comment] 2024-08-29 06:15
CMBaseSpeciesOrganic needs explosion resistance for contents inside of it, like bags and such. In CM throwing a grenade with a larva in a host does no damage to the larva

**Comment by Dutch-VanDerLinde** [comment] 2024-11-06 14:44
Cannot reproduce

**Comment by Vermidia** [comment] 2024-11-06 14:47
This should be fixed by #4595 hopefully, since there should now be no way for larva to die within a host when already spawned...hopefully

**Closed by Vermidia** 2024-11-06 14:47 UTC
Labels: Issue: Bug
