### ISSUE TITLE
You Can Vault Over Barbed Cades With Tables

### ISSUE THREAD

**Issue by Kezu02** [RMC-14/RMC-14#3845] opened 2024-08-26 07:51 UTC
## Description

Title.

**Screenshots**

![image](https://github.com/user-attachments/assets/aa6b4d0c-4d15-4833-9e36-965957ebcb7f)
![image](https://github.com/user-attachments/assets/f8cc1076-414f-4bee-b8c8-a083700dcf6a)

**Comment by Vermidia** [comment] 2024-08-26 07:53
Dupe of #3575

**Closed by Vermidia** 2024-08-26 07:53 UTC
Labels: Status: Untriaged
