### ISSUE TITLE
Bionic SMG implant

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#3795] opened 2024-08-22 16:56 UTC
## Description
You can fuse SMGs to your arms

**Reproduction**
Hold SMG with SMG brace.
Activate brace
Use second hand to attach Solid SMG stock 
You now have a perma SMG fused to your arm

**Comment by Siigiil** [comment] 2024-08-23 02:22
Duplicate of #3570. Fix has been up for a while, though not merged yet.

**Closed by Siigiil** 2024-08-23 02:22 UTC
Labels: duplicate, Issue: Bug
