### ISSUE TITLE
Hive weed prevents plasma regen(?)

### ISSUE THREAD

**Issue by Alekshhh** [RMC-14/RMC-14#5014] opened 2024-12-01 19:50 UTC
heard queens say it prevents regen, although I sometimes see it working just fine. need elaboration

stinks for queen especially

if this is parity what the fuck cm13 coders

**Comment by Vermidia** [comment] 2024-12-01 22:24
I think hive weeds aren't being assigned a hive member component properly? Xenos can currently break them, and gardeners might not be able to plant on them, but not sure if anyones tested the later.

**Comment by Alekshhh** [comment] 2024-12-03 15:18
the healing may be due to a queen being in ovi, and then the weeds replacing regular weeds. since you need to move to register being on weeds, and queen is in place, it does not count her as being on weeds, so it denies regen

**Comment by Skarletto** [comment] 2024-12-31 08:28
I can't reproduce it anymore and afaik it hasn't been an issue for a little bit, I tried to find an issue to link but for some reason I can't find any
closing but feel free to reopen/make a new issue if its still happening

**Closed by Skarletto** 2024-12-31 08:28 UTC
Labels: Status: Untriaged
