### ISSUE TITLE
bipod is bipolar

### ISSUE THREAD

**Issue by deltanedas** [RMC-14/RMC-14#3727] opened 2024-08-19 00:12 UTC
## Description
it will seemingly randomly decide to stop working, so when you think you are going to rain hell on xenos it just doesnt with no warning of any kind
also it waits until you shoot to undeploy instead of as soon as you move cursor or whatever causes it to have a stroke, so you have to constantly toggle it just to be safe

**Comment by ARMOKS** [comment] 2024-08-19 00:19
This happens when you set up on a barricade or similar thing, as the thing you setup on is only good for one direction, meaning if the game chooses that your setup is wrong it just kills it, very janky but kinda working as intended

**Comment by ARMOKS** [comment] 2024-08-19 00:20
For example if I setup here while facing left, even tho I setup a west facing bipod, the north cade makes me only able to shoot the gun north with the bipod perks
![image](https://github.com/user-attachments/assets/151933c9-ee1a-4fb2-8371-628d55a65a06)

**Comment by deltanedas** [comment] 2024-08-19 01:23
it should just restrict your direction and firing to wherever it gets set up on instead of this trollage (which you also have no way of knowing if you are at a corner, since "barricade" can mean either side)

**Comment by Siigiil** [comment] 2024-08-19 02:18
> it should just restrict your direction and firing to wherever it gets set up on

It already does. It locks the valid shot direction to wherever you were facing when you activated the bipod.

This just apparently either doesn't always work. Or *something else* makes it think you're turning when you aren't. And I have no idea what that *something* is.

**Comment by Rainbeon** [comment] 2024-11-15 05:32
I have found the source of this. Bipods (and all attachments) do *not* remove their comps upon manual untoggling, they currently only do so when you hit their fail condition (shooting at a bad angle for the direction locks, and moving for the movement locks). As a result, the next time you re-toggle them, they will still have the lock data as the last time you manually untoggled it.

This was not apparent because for some reason Unscoping is hardcoded to happen and just entirely ignore their direction locked component, and it is the only other user of this.

**Comment by Rainbeon** [comment] 2024-12-09 22:37
Fixed by #4832

**Closed** 2024-12-09 22:47 UTC
Labels: Issue: Bug
