### ISSUE TITLE
Queen screech stunning is inconsistent 

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [RMC-14/RMC-14#3005] opened 2024-07-12 07:27 UTC
## Description
myself and other players have noticed that the queens screech isn't stunning people as it should, sometimes not even stunning people a single tile away.

**Comment by ShadowCommander** [comment] 2024-07-12 07:28
Duplicate of #3000
Fixed by #3002

**Closed** 2024-07-12 07:28 UTC
Labels: Status: Untriaged
