### ISSUE TITLE
Marine Armor light can be turned back on while devoured

### ISSUE THREAD

**Issue by Rainbeon** [RMC-14/RMC-14#4014] opened 2024-09-12 01:11 UTC
## Description
Devouring normally turns the devoured marine's armor light off, however, marines can just turn it right back on again as soon as they are actionable with the knife. Unsure of what is parity, but this seems unintended as it makes devouring turning off the light fairly pointless.

**Reproduction**
1) Get devoured as marine
2) Wait a few seconds until you can pull out your knife
3) Press the armor light toggle hotkey/button

**Comment by Vermidia** [comment] 2024-09-12 01:12
Dupe of #3896

**Closed by Vermidia** 2024-09-12 01:12 UTC
Labels: Status: Untriaged
